include: /build/gitlab-ci.yml

variables:
  LLVM_VERSION: "3.9.1"
  PROJECT_PATH: "sosy-lab/software/llvm-j"
  GH_REF: "github.com/sosy-lab/llvm-j"

download-lib:
  stage: dependencies
  script: "ant -verbose download-library -Dllvm.version=$LLVM_VERSION"
  artifacts:
    paths:
      - lib/native

# Run unit tests with dependency on download-lib
unit-tests:jdk-11:
  dependencies:
    - build-dependencies
    - build:jdk-11
    - download-lib

bindings-build:
  # Put in stage 'checks' to make other checks not dependent on its failure
  stage: checks
  dependencies:
    - build-dependencies
  script:
    - "ant bindings -Dllvm.home=/usr/include/llvm-c-3.9/llvm-c"
    - "git diff --exit-code"


## Currently disabled runs ##

# We currently don't have a JDK-14 image with LLVM 3.9 installed
build:jdk-14:
  only:
    - web

build-project-ecj:jdk-14:
  only:
    - web

unit-tests:jdk-14:
  dependencies:
    - build-dependencies
    - build:jdk-14
    - download-lib
  only:
    - web

reuse:
  only:
    - web
