git:
  depth: 1
cache:
  directories:
    - $HOME/.ivy2

language: java
jdk:
  - oraclejdk8
os: linux
dist: xenial
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-6
            - chrpath
env:
    global:
        - GH_REF: github.com/sosy-lab/llvm-j.git
        - LLVM_VERSION: 3.9.1
install:
  - ant build-dependencies
  - ant -verbose download-library -Dllvm.version=$LLVM_VERSION
matrix:
    include:
      - env: NAME='Build with ECJ'
        script:
          - ant build-project-ecj
      - env: NAME='Create Javadoc'
        script:
          - ant javadoc
      - env: NAME=Checkstyle
        script:
          - ant run-checkstyle -Dcheckstyle.output=plain && cat Checkstyle*.xml && test $(cat Checkstyle*xml | grep -vic audit) -eq 0
      - env: NAME=SpotBugs
        script:
          - ant spotbugs -Dspotbugs.output=text && cat SpotBugs.xml && test \! -s SpotBugs.xml
      - env: NAME='Check source-code format'
        script:
          - ant format-source && git diff -s --exit-code

      - env: NAME="Unit Tests"
        script:
          - ant -verbose unit-tests
