/**
 * Java bindings for the LLVM C library.<br />
 * The bindings in {@link org.sosy_lab.llvm_j.binding.LLVMLibrary LLVMLibrary} are
 * automatically generated by JNAerator.
 * It is advised not to use these directly, but use the classes in {@link org.sosy_lab.llvm_j}
 * to access them.
 */
package org.sosy_lab.llvm_j.binding;